/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import datos.EjemplarData;
import datos.LibroData;
import entidades.Ejemplar;
import entidades.Libro;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author conandoel
 */
public class AgregarEjemplarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarEjemplarView
     */
    List<Libro> libros=new ArrayList<>();
    public AgregarEjemplarView() {
        initComponents();
        cargarcbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbLibros = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcbEditoriales = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLFoto = new javax.swing.JLabel();

        jLabel1.setText("Libro:");

        jLabel2.setText("Agregar Ejemplar");

        jcbLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLibrosActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Editorial:");

        jcbEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEditorialesActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(83, 114));

        jLFoto.setText("libro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFoto)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFoto)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jcbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jcbEditoriales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcbLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbEditoriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EjemplarData ed=new EjemplarData();
        Ejemplar ejemplar=new Ejemplar();
        for(Libro libro:libros){
            if(libro.getTitulo().equals(jcbLibros.getSelectedItem().toString()) && libro.getEditorial().equals(jcbEditoriales.getSelectedItem().toString())){
                ejemplar.setEstado("Disponible");
                ejemplar.setLibro(libro);
                ed.agregarEjemplar(ejemplar);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLibrosActionPerformed
        // TODO add your handling code here:
        limpiarEditoriales();
        for(Libro libro:libros){
            if(libro.getTitulo().equals(jcbLibros.getSelectedItem().toString())){
                jcbEditoriales.addItem(libro.getEditorial());
                
                cargarFotoLibro(libro.getIsbn());
            }
        }
    }//GEN-LAST:event_jcbLibrosActionPerformed

    private void jcbEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEditorialesActionPerformed
        // TODO add your handling code here:
        
//        for(Libro libro:libros){
//            if(libro.getTitulo().equals(jcbLibros.getSelectedItem().toString())&&libro.getEditorial().equals(jcbEditoriales.getSelectedItem().toString())){
//                cargarFotoLibro(libro.getIsbn());
//            }
//        }
    }//GEN-LAST:event_jcbEditorialesActionPerformed

    private void cargarcbl(){
        LibroData ld=new LibroData();
        libros=ld.listarLibroSinAutor();
        int cont=0;
        for(Libro libro:libros){
            for(int i=0;i<jcbLibros.getItemCount();i++){
                if(libro.getTitulo().equals(jcbLibros.getItemAt(i).toString())){
                   cont++;
                }
            }
            if(cont==0){
            jcbLibros.addItem(libro.getTitulo());
            }else{cont=0;}
        }
    }
    private void limpiarEditoriales(){
        int j=jcbEditoriales.getItemCount();
        System.out.println("cantidad de editoriales "+j);
        if(j>0){
        try{
            for(int i=j-1;i>=0;i--){
                jcbEditoriales.removeItemAt(i);
                System.out.println("quita el "+i);
            }
        }catch(NullPointerException ex){
        
        }
        }
        
    }
    private void cargarFotoLibro(long isbn){
        try {
            File file = new File("./src/vistas/libros/" + isbn + ".jpg");
            //Se  lee una imagen desde un archivo y se almacena en una variable de tipo BufferedImage
            BufferedImage fotoPerfil = ImageIO.read(file);
            
            //Se borra el texto POR DEFECTO "Imagen" del JLabel y se establece su tamaño contenedor
            jLFoto.setText("");
            jLFoto.setSize(82, 113);
            //Se dimensiona la IMAGEN para que tenga el mismo largo y ancho del JLabel
            Image dFotoPerfil = fotoPerfil.getScaledInstance(jLFoto.getWidth(), jLFoto.getHeight(), Image.SCALE_SMOOTH);
            //Se pone la imagen en el JLabel usando setIcon()
            jLFoto.setIcon(new ImageIcon(dFotoPerfil));
        } catch (IOException ex) {
            Logger.getLogger(PrestamosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbEditoriales;
    private javax.swing.JComboBox<String> jcbLibros;
    // End of variables declaration//GEN-END:variables
}
