/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import datos.PrestamoData;
import entidades.Prestamo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author conandoel
 */
public class BuscarPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPrestamoView
     */
    private DefaultTableModel modelo=new DefaultTableModel();
    List<Prestamo> prestamos=new ArrayList<>();
    public BuscarPrestamoView() {
        initComponents();
        cargarTabla();
        PrestamoData pd=new PrestamoData();
        prestamos=pd.listarPrestamos();
        cargaTablaCompleta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaPrestamos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfPrestamo = new javax.swing.JTextField();
        jbtnEliminar = new javax.swing.JButton();

        jtListaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtListaPrestamos);

        jLabel1.setText("Prestamo:");

        jtfPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPrestamoKeyReleased(evt);
            }
        });

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnEliminar)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnEliminar)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPrestamoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrestamoKeyReleased
        // TODO add your handling code here:
        limpiarTabla();
        if(jtfPrestamo.getText().equals("")){
           cargaTablaCompleta();
        }else{
            for(Prestamo prestamo:prestamos){
                if(String.valueOf(prestamo.getIdPrestamo()).startsWith(jtfPrestamo.getText())){
                    modelo.addRow(new Object[]{prestamo.getIdPrestamo(),prestamo.getLector().getIdSocio(),prestamo.getEjemplar().getCodigo(),prestamo.getFechaInicio(),prestamo.getFechaFin()});
                }
            }
        }
    }//GEN-LAST:event_jtfPrestamoKeyReleased

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        if(jtListaPrestamos.getSelectedRow()>-1){
            int idej=jtListaPrestamos.getSelectedRow();
            int cel=Integer.parseInt(jtListaPrestamos.getValueAt(idej, 0).toString());
            PrestamoData pd=new PrestamoData();
            pd.eliminarPrestamos(cel);
            jtfPrestamo.setText("");
            limpiarTabla();
            prestamos=pd.listarPrestamos();
            cargaTablaCompleta();
        }else{
            JOptionPane.showMessageDialog(null, "Debe elegir un prestamo de la tabla");
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void limpiarTabla(){
        int f=modelo.getRowCount()-1;
        for(;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    private void cargarTabla(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Socio");
        modelo.addColumn("Ejemplar");
        modelo.addColumn("Fecha Pres.");
        modelo.addColumn("Fecha Dev.");
        jtListaPrestamos.setModel(modelo);
    }
    
    private void cargaTablaCompleta(){
        for(Prestamo prestamo:prestamos){
            modelo.addRow(new Object[]{prestamo.getIdPrestamo(),prestamo.getLector().getIdSocio(),prestamo.getEjemplar().getCodigo(),prestamo.getFechaInicio(),prestamo.getFechaFin()});

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEliminar;
    public javax.swing.JTable jtListaPrestamos;
    public javax.swing.JTextField jtfPrestamo;
    // End of variables declaration//GEN-END:variables
}
