/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import datos.PrestamoData;
import entidades.Prestamo;
import java.time.ZoneId;
import java.util.ArrayList;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author conandoel
 */
public class ModificarPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarPrestamoView
     */
    List<Prestamo> prestamos=new ArrayList<>();
    public ModificarPrestamoView() {
        initComponents();
        cargarPrestamos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfIdPrestamo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtLibro = new javax.swing.JTextField();
        jtEjemplar = new javax.swing.JTextField();
        jtSocio = new javax.swing.JTextField();
        jtFechaPrestamo = new javax.swing.JTextField();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        jcheckEstado = new javax.swing.JCheckBox();
        jbtnModificar = new javax.swing.JButton();

        jLabel1.setText("Prestamo:");

        jtfIdPrestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfIdPrestamoKeyReleased(evt);
            }
        });

        jLabel2.setText("Libro:");

        jLabel3.setText("Ejemplar:");

        jLabel4.setText("Socio:");

        jLabel5.setText("Fecha Prestamo:");

        jLabel6.setText("Fecha Devolucion:");

        jLabel7.setText("Estado:");

        jcheckEstado.setText("Habilitado");

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jtFechaPrestamo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtEjemplar)
                            .addComponent(jtSocio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtnModificar)
                                .addComponent(jcheckEstado)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jdcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcheckEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jbtnModificar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdPrestamoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdPrestamoKeyReleased
        // TODO add your handling code here:
        
        if(jtfIdPrestamo.getText().equals("")){
            
        }else{
            for(Prestamo prestamo:prestamos){
                if(String.valueOf(prestamo.getIdPrestamo()).startsWith(jtfIdPrestamo.getText())){
                    jtLibro.setText(prestamo.getEjemplar().getLibro().getTitulo());
                    jtLibro.setEditable(false);
                    jtEjemplar.setText(String.valueOf(prestamo.getEjemplar().getCodigo()));
                    jtEjemplar.setEditable(false);
                    jtSocio.setText(String.valueOf(prestamo.getLector().getIdSocio()));
                    jtSocio.setEditable(false);
                    jtFechaPrestamo.setText(prestamo.getFechaInicio().toString());
                    jtFechaPrestamo.setEditable(false);
                    jdcFechaFin.setDate(java.sql.Date.valueOf(prestamo.getFechaFin()));
                    if(prestamo.isEstado()){
                        jcheckEstado.setSelected(true);
                        jcheckEstado.setText("Habilitado");
                    }else{
                        jcheckEstado.setSelected(false);
                        jcheckEstado.setText("Des Habilitado");
                    }
                }
            }
        }
        
    }//GEN-LAST:event_jtfIdPrestamoKeyReleased

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        // TODO add your handling code here:
        if(jtfIdPrestamo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Dede ingresar un prestamo");
        }else{
            Prestamo prestamo=new Prestamo();
            prestamo.setIdPrestamo(Integer.parseInt(jtfIdPrestamo.getText()));
            prestamo.setEstado(jcheckEstado.isSelected());
            prestamo.setFechaFin(jdcFechaFin.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            PrestamoData pd=new PrestamoData();
            pd.modificarPrestamo(prestamo);
        }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void cargarPrestamos(){
        PrestamoData pd=new PrestamoData();
        prestamos=pd.listarPrestamosSC();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JCheckBox jcheckEstado;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private javax.swing.JTextField jtEjemplar;
    private javax.swing.JTextField jtFechaPrestamo;
    private javax.swing.JTextField jtLibro;
    private javax.swing.JTextField jtSocio;
    private javax.swing.JTextField jtfIdPrestamo;
    // End of variables declaration//GEN-END:variables
}
